// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TP_Entity_FirstTP.Database;

#nullable disable

namespace TP_Entity_FirstTP.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20240326155748_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("TP_Entity_FirstTP.Models.Animal", b =>
                {
                    b.Property<int>("AnimalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AnimalEspece")
                        .HasColumnType("longtext");

                    b.HasKey("AnimalId");

                    b.ToTable("Animals");

                    b.HasData(
                        new
                        {
                            AnimalId = 1,
                            AnimalEspece = "Chat"
                        },
                        new
                        {
                            AnimalId = 2,
                            AnimalEspece = "Chien"
                        },
                        new
                        {
                            AnimalId = 3,
                            AnimalEspece = "Renard"
                        },
                        new
                        {
                            AnimalId = 4,
                            AnimalEspece = "Loutre"
                        },
                        new
                        {
                            AnimalId = 5,
                            AnimalEspece = "Poney"
                        },
                        new
                        {
                            AnimalId = 6,
                            AnimalEspece = "Corbeau"
                        });
                });

            modelBuilder.Entity("TP_Entity_FirstTP.Models.Client", b =>
                {
                    b.Property<int>("ClientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClientNom")
                        .HasColumnType("longtext");

                    b.HasKey("ClientId");

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            ClientId = 1,
                            ClientNom = "Jeanne"
                        },
                        new
                        {
                            ClientId = 2,
                            ClientNom = "Maurice"
                        },
                        new
                        {
                            ClientId = 3,
                            ClientNom = "Lison"
                        });
                });

            modelBuilder.Entity("TP_Entity_FirstTP.Models.Reservation", b =>
                {
                    b.Property<int>("ReservationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("ReservationAnimalAnimalId")
                        .HasColumnType("int");

                    b.Property<int?>("ReservationClientClientId")
                        .HasColumnType("int");

                    b.HasKey("ReservationId");

                    b.HasIndex("ReservationAnimalAnimalId");

                    b.HasIndex("ReservationClientClientId");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("TP_Entity_FirstTP.Models.Reservation", b =>
                {
                    b.HasOne("TP_Entity_FirstTP.Models.Animal", "ReservationAnimal")
                        .WithMany()
                        .HasForeignKey("ReservationAnimalAnimalId");

                    b.HasOne("TP_Entity_FirstTP.Models.Client", "ReservationClient")
                        .WithMany()
                        .HasForeignKey("ReservationClientClientId");

                    b.Navigation("ReservationAnimal");

                    b.Navigation("ReservationClient");
                });
#pragma warning restore 612, 618
        }
    }
}
